services:
  vpnserver:
    build: ./vpnserver
    container_name: vpnserver
    cap_add:
      - NET_ADMIN
      - MKNOD
    devices:
      - /dev/net/tun:/dev/net/tun
    # Puertos est치ndar de Access Server:
    ports:
      - "943:943/tcp"    # Admin & Client Web UI
      - "443:443/tcp"    # OpenVPN TCP + port sharing con Web UI
      - "1194:1194/udp"  # OpenVPN UDP
    environment:
      # Passwords para usuarios A y B (c치mbialos en producci칩n)
      - USER_A=A
      - PASS_A=A_password
      - USER_B=B
      - PASS_B=B_password
      # Nombre que meteremos en la config del servidor (.ovpn apuntar치 a esto)
      - AS_HOSTNAME=vpnserver
      # Habilitar TLS-crypt v2 en perfiles (si tu cliente lo soporta)
      - ENABLE_TLS_CRYPT_V2=true
    volumes:
      - ovpn-as-data:/openvpn
      - clients-configs:/clients
    restart: unless-stopped
    networks:
      - lan

  client-a:
    build: ./client
    container_name: client-a
    depends_on:
      - vpnserver
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - CLIENT_NAME=A
      - CLIENT_USER=A
      - CLIENT_PASS=A_password
      - HELLO_TEXT=Hello from A
      - HTTP_PORT=8080
    volumes:
      - clients-configs:/clients:ro
    restart: unless-stopped
    networks:
      - lan

  client-b:
    build: ./client
    container_name: client-b
    depends_on:
      - vpnserver
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - CLIENT_NAME=B
      - CLIENT_USER=B
      - CLIENT_PASS=B_password
      - HELLO_TEXT=Hello from B
      - HTTP_PORT=8080
    volumes:
      - clients-configs:/clients:ro
    restart: unless-stopped
    networks:
      - lan
  kali-c:
    image: kasmweb/core-kali-rolling:1.18.0-rolling-daily
    container_name: kali-c
    shm_size: "2g"
    user: root  # Iniciar como root para poder modificar usuarios
    environment:
      - VNC_PW=kalipass
      - PROXY_MODE=none
    ports:
      - "6901:6901"
    volumes:
      - kali-home:/home/kasm-user
    networks:
      - lan
    restart: unless-stopped
    command: >
      bash -c "
      usermod -aG sudo kasm-user &&
      echo 'kasm-user:kalipass' | chpasswd &&
      exec /dockerstartup/kasm_default_profile.sh /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh
      "
volumes:
  ovpn-as-data:
  clients-configs:
  kali-home:

networks:
  lan:
    driver: bridge

