networks:
  lan_a:
    driver: bridge
    ipam:
      config: [ { subnet: 172.100.0.0/24 } ]
  lan_b:
    driver: bridge
    ipam:
      config: [ { subnet: 172.200.0.0/24 } ]

services:
  ubuntu-a:
    build: ./vpnnode
    container_name: ubuntu-a
    cap_add: [ "NET_ADMIN" ]
    devices: [ "/dev/net/tun:/dev/net/tun" ]
    sysctls:
      net.ipv4.ip_forward: "1"
    environment:
      - OVPN_CONFIG_PATH=/etc/openvpn/server.conf
    volumes:
      - ./config/a:/etc/openvpn
    networks:
      lan_a:
        ipv4_address: 172.100.0.10
    ports:
      - "1194:1194/udp"

  ubuntu-b:
    build: ./vpnnode
    container_name: ubuntu-b
    cap_add: [ "NET_ADMIN" ]
    devices: [ "/dev/net/tun:/dev/net/tun" ]
    sysctls:
      net.ipv4.ip_forward: "1"
    environment:
      - OVPN_CONFIG_PATH=/etc/openvpn/client.conf
    volumes:
      - ./config/b:/etc/openvpn
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      lan_b:
        ipv4_address: 172.200.0.10